### ISSUE TITLE
typo報告

### ISSUE THREAD

**Issue by keijidosha** [sakura-internet/cloud-manual#1]
URL: [ネットワーク設定について](https://manual.sakura.ad.jp/cloud/support/technical/network-settings.html)

typoを報告させていただきます。よろしくお願いします。

(誤) 同一仮想サーバに搭載された複数のNICをは同一のスイッチ
(正) 同一仮想サーバに搭載された複数のNICを同一のスイッチ

**Comment by zembutsu** [comment]
@keijidosha ご指摘ありがとうございました。
対象ページを書き換えましたのでご報告とさせていただきます。
`複数のNICをは` を、 `複数のNICは、` と句読点を入れ、文章を変更させていただきました。
