### ISSUE TITLE
コマンド体系を新しいものに合わせた方が今風かもです。

### ISSUE THREAD

**Issue by tomokitamaki** [sakura-internet/cloud-manual#10]
# 概要

すごく細かいことでアレなのですが、  
docker tag や docker push ではなく、 docker image tag や docker image push のほうが良かもです。

# 内容

[docs.docker.comのreference](https://docs.docker.com/engine/reference/commandline/image_tag/) 的にはマニュアルに記載している `docker tag` や `docker push` ではなく、  
```bush
docker image tag
docker image push
```
を推奨しているようなので、新しい体系のコマンドに合わせた方がユーザにとって、  
混乱？がなくて良いかもと思いました。  

URL: [コンテナレジストリ(Lab)](https://manual.sakura.ad.jp/cloud/appliance/container-registry/index.html)

**Comment by yuto** [comment]
ご意見ありがとうございます。
マニュアルではあくまで参考情報として掲載しており、より短いdocker tagやdocker pushをコマンド例として例示しました。
詳しいご利用方法については引き続き各自ドキュメントの参照をお願いする形式としたいと思うので、ひとまずこのままとしたいと思います。
docker image * コマンドがより推奨される状況になりましたら変更を検討します。
