### ISSUE TITLE
vSRX

### ISSUE THREAD

**Issue by na8esin** [sakura-internet/cloud-manual#11]
URL: [vSRX](https://manual.sakura.ad.jp/cloud/marketplace/vsrx.html)

![コメント 2020-01-14 161938](https://user-images.githubusercontent.com/12827148/72322436-afa00080-36e9-11ea-9eac-af963837b597.png)

**Comment by yuto** [comment]
ご連絡ありがとうございました。
修正対応を完了いたしました。

**Comment by na8esin** [comment]
対応ありがとうございます。確認いたしましたm(_ _)m
