### ISSUE TITLE
「アプライアンス関連API」へのリンクが不正

### ISSUE THREAD

**Issue by mattn** [sakura-internet/cloud-manual#13]
URL: [ショートメッセージサービス](https://manual.sakura.ad.jp/cloud/shortmessage/index.html)

> さくらのクラウドAPIの利用方法など、一般的な情報については APIドキュメント を参照ください。
また、基本的なアプライアンスの操作については アプライアンス関連API をご参照ください。

この「アプライアンス関連API」の部分のリンクが `test.developer.` になっている様です。おそらく `test.` が必要ないです。

**Comment by yuto** [comment]
ご連絡ありがとうございます。さくらインターネットの大井です。
ご指摘の通り `test` が余計でしたので削除を行いました。
Issues報告へのご協力ありがとうございました。
