### ISSUE TITLE
サイト間VPNのFortiOS5系設定例について

### ISSUE THREAD

**Issue by mori-takahiro370** [sakura-internet/cloud-manual#15]
URL: [サイト間VPN アプライアンス側設定例 Fortinet Fortigateシリーズ FortiOS5系][(https://manual.sakura.ad.jp/cloud/network/vpc-router/vpc-site-to-site-vpn-appliance-settings.html](https://manual.sakura.ad.jp/cloud/network/vpc-router/vpc-site-to-site-vpn-appliance-settings.html#fortinet-fortigate-fortios5))
項番9,10について、diffie-hellmanグループの2にチェックを入れないと接続できませんでした。

**Comment by yuto** [comment]
さくらインターネットの大井と申します。
フィードバックありがとうございました。ご指摘の部分、確かに間違いと確認いたしましたのでマニュアルの修正を行いました。
ご連絡が遅くなり大変申し訳ございませんでした。
