### ISSUE TITLE
Wireguardのプロトコル

### ISSUE THREAD

**Issue by chokkoyamada** [sakura-internet/cloud-manual#16]
URL: [WireGuardサーバ機能](https://manual.sakura.ad.jp/cloud/network/vpc-router/vpc-wireguard.html)

>ポート  TCP 51820

となっていますがWireguardなのでUDPではないかと思いました。
実際に動作確認したわけではないですが、気づいたのでご指摘まで。

**Comment by yuto** [comment]
さくらインターネットの大井と申します。
弊社内でも正しくはUDPであることを確認し、該当ページの記述の修正を完了いたしました。
フィードバックへのご協力ありがとうございました。
