### ISSUE TITLE
タグの数の制限が10個

### ISSUE THREAD

**Issue by ak1ra24** [sakura-internet/cloud-manual#17]
URL: [タグ機能](https://manual.sakura.ad.jp/cloud/controlpanel/tag.html)

サーバーにタグを10個以上つけたところ、以下のようなエラーが発生しています
```
不適切な要求です。パラメータの指定誤り、入力規則違反です。入力内容をご確認ください。\nServer.Tags must be in tags format
```

サーバーのタグの個数に制限があることを記載してもらいたいです

**Comment by yuto** [comment]
さくらインターネットの大井と申します。
フィードバックありがとうございました。マニュアルを確認し、タグの上限数についての記載がございませんでしたので追記を行いました。
https://manual.sakura.ad.jp/cloud/controlpanel/tag.html#id4

今後も品質向上のため最大限対応させていただきますので、お気づきの点がございましたらお気軽にフィードバックいただけますと幸いです。
