### ISSUE TITLE
DMARK という記載があるが、おそらくDMARC の間違い

### ISSUE THREAD

**Issue by moeyashi** [sakura-internet/cloud-manual#18]
URL: [DNS(アプライアンス)](https://manual.sakura.ad.jp/cloud/appliance/dns/index.html)

**Comment by yuto** [comment]
さくらインターネットの大井と申します。

この度はフィードバックありがとうございました。
ご指摘のとおり記載の箇所は誤記でした。しかしながら該当箇所の周辺を含めて全体的に見直したところ、
本来DNSレコードとして存在するのはSPFレコードのみであり、DKIMやDMARCを同列に記載したままでは
誤解を招く恐れがあったため、これらの記載自体を削除した上で文言の修正を行いました。

また何かお気づきの点やご不明な点がありましたらお知らせください。
