### ISSUE TITLE
記事中のリンクの案内について

### ISSUE THREAD

**Issue by civuta** [sakura-internet/cloud-manual#20]
URL: [nRF9160(nRF9160-DK)](https://manual.sakura.ad.jp/cloud/mobile-connect/compatiblity/nrf9160-dk.html)

nRF9160-DK 動作確認時仕様と同じ仕様のボード、ファームウェアを書き込んでnRF9160-DK付属のi-basis SIMで接続を試みようとしています。
見当違いな質問でしたらすみませんが、

> [nRF9160-DKの事前設定](https://manual.sakura.ad.jp/cloud/mobile-connect/compatiblity/nrf9160-dk.html#id19)
> 
> [Getting started with nRF9160 DK](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_nrf9160_gs.html) の、Minimum requirements、Updating the DK firmwareの項を参考に、 nRF9160-DK application and modem firmwareとnRF9160 SiP modem firmwareを整えてください。

とありますが、Updating the DK firmware　とは、リンク先のどの記述でしょうか。

**Comment by homare222** [comment]
Nordic Semiconductor社のドキュメントサイト再編等によりご質問にある項目(Updating the DK firmware)がなくなってしまいましたので、かわりにGetting started with nRF9160 DK  - Getting started using Quick Start をご参照ください。

Getting started with nRF9160 DK  - Getting started using Quick Start
https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/gsg_guides/nrf9160_gs.html#getting_started_using_quick_start

上記に記載のある Quick Start application を利用することで簡易に動作確認ができます。
なお、Quick Start application の Select an application to program において AT Commands (Serial LTE Modem) のプログラムを選択することで、[nRF9160(nRF9160-DK) | さくらのクラウド マニュアル](https://manual.sakura.ad.jp/cloud/mobile-connect/compatiblity/nrf9160-dk.html) に記載されている動作確認が可能な状態となります。

**Comment by homare222** [comment]
ファームウェアの更新については、以下の新しいドキュメントをご参照ください。

Updating the DK firmware using Programmer
https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/app_dev/device_guides/nrf91/nrf91_dk_updating_fw_programmer.html

**Comment by yuto** [comment]
civuta様

お問い合わせありがとうございます。さくらインターネットの大井と申します。
一旦担当より回答させていただきましたので、ご参考いただけますと幸いです。

本issueについてはクローズさせていただきますが、また不明な点がございましたら
再度お問い合わせいただきますようお願いいたします。

**Comment by civuta** [comment]
さくらインターネット　大井様
お世話になっております。
上記クローズ承知しました。

よろしくお願いします。
