### ISSUE TITLE
管理者用ガイドPDFの誤り

### ISSUE THREAD

**Issue by s-koori** [sakura-internet/cloud-manual#23]
URL: [EGセキュアソリューションズ株式会社 SiteGuard Server Edition ご利用ガイド](https://manual.sakura.ad.jp/cloud/securearea/siteguardserveredition.html)
このページからリンクしているPDF [SiteGuard Server Edition Apache版 管理者用ガイド](https://manual.sakura.ad.jp/cloud/_downloads/siteguard-server-edition-700-3_apache.pdf) の内容で1箇所（1文字）誤りがあります。

該当箇所: p.132 「10.2 検出名」
\- アクセス制御
誤
> RULE_ACCESS/[検出箇所]:[名前]

正
> RULE_ACCESS/[検出箇所]/[名前]

**Comment by yuto** [comment]
さくらインターネットの大井と申します。
ご指摘いただいたとおり該当部分は誤記でしたので修正を行い、正しい記載のPDFファイルと差し替えを行いました。
ご連絡ありがとうございました。
