### ISSUE TITLE
画像の見れない

### ISSUE THREAD

**Issue by hatano0x06** [sakura-internet/cloud-manual#3]
URL: [ルータ＋スイッチを使ったネットワークを構築してみよう – 「楽しいさくらのクラウド」(6)](https://knowledge.sakura.ad.jp/1343/)

”「ルーター」＋「スイッチ」設定画”以降の画像が見れていません
リンクコピーで開くと見れます
windows10のedge、chromeで確認しましたが、どちらも同じ現象でした

**Comment by zembutsu** [comment]
@hatano0x06 ご連絡ありがとうございます。
対象のページ状態については確認中です。
お待ちをいただきますようお願いいたします。

**Comment by zembutsu** [comment]
@hatano0x06 ご連絡いただいた件、画像が表示できるように調整いたしました。
お手数ですが、ご確認いただけますでしょうか。

この度はご連絡をいただき、大変ありがとうございました 🙇
