### ISSUE TITLE
プラン変更が出来ない認識ですが、明確に書いて有る方が良いと思います。

### ISSUE THREAD

**Issue by terao** [sakura-internet/cloud-manual#4]
URL: [データベースアプライアンスとは](https://manual.sakura.ad.jp/cloud/appliance/database/about.html)

**Comment by yuto** [comment]
https://github.sakura.codes/sakura-manual/cloud/pull/716/files
作成操作の項目で
> 選択したプランは作成後に変更することはできません。
の注記を追加しました。

**Comment by dalice** [comment]
フィードバックありがとうございました
