### ISSUE TITLE
リソースの破棄

### ISSUE THREAD

**Issue by terao** [sakura-internet/cloud-manual#5]
さくナレなどで、
```
トライアルが終わったらリソースマネージャーで作成したリソースを破棄してください。具体的なやり方はこちらのマニュアルをご覧ください。
```

と書きたいときがあるので、テンプレートの削除の上あたりに、

「コマンドから破棄を選択すると作成されたリソースがすべて削除されます。削除した物を復活することは出来ません」

と言う旨が書いてある小見出しが欲しいです。

URL: [コントロールパネルと機能詳細](https://manual.sakura.ad.jp/cloud/resource-manager/controlpanel.html)

**Comment by yuto** [comment]
以下の差分の通り注意書きを追記しました。
https://github.sakura.codes/sakura-manual/cloud/pull/715/files
> 「破棄」を選択すると、作成されたリソースがすべて削除されます。削除後は復活することができませんのでご注意ください。

なお、コントロールパネル上では「破棄」選択後、以下のような警告表示が行われます。

> 破棄
> 
> 破棄を実行します
> 関連するリソースがすべて削除されます
> バックグラウンドで実行されます。進捗の確認は詳細ページのログを参照ください。
> [キャンセル] [破棄]

**Comment by dalice** [comment]
フィードバックありがとうございました
