### ISSUE TITLE
証明書更新APIはPOSTメソッドしか受け付けない

### ISSUE THREAD

**Issue by upsilon** [sakura-internet/cloud-manual#7]
URL: [公開API](https://manual.sakura.ad.jp/cloud/webaccel/api.html)

ウェブアクセラレータの証明書更新APIについて、PUTメソッドと記載されていますが実際にはPOSTメソッドしか受け付けません。
https://manual.sakura.ad.jp/cloud/webaccel/api.html#id19

**Comment by dalice** [comment]
ご連絡ありがとうございます。

現時点では公開APIとしては"更新"のみをサポートしております。
更新についてはPUTで行うため、ドキュメントではPUTとしております。

新規登録（証明書の初回登録）はPOSTで行えますが、ドキュメントとしては公開しておらず、
新規登録のAPI実行は公式にはサポートの範囲としておりません。

今後、新規登録（証明書の初回登録）をAPIドキュメントでの公開を含め検討させていただきます。

**Comment by masa23** [comment]
本日 新規登録（証明書の初回登録）および、証明書の状態を確認するAPIを
公開APIとして追加させていただきました。

https://manual.sakura.ad.jp/cloud/webaccel/api.html

**Comment by upsilon** [comment]
対応ありがとうございます🙇
