### ISSUE TITLE
Android誤記

### ISSUE THREAD

**Issue by Nyuuki0224** [sakura-internet/cloud-manual#8]
下記ページ3箇所が `Android`ではなく `Andriod`表記になっている。

https://manual.sakura.ad.jp/cloud/mobile-connect/sim/device-settings.html?highlight=andriod

![image](https://user-images.githubusercontent.com/19767337/64146159-da826a00-ce56-11e9-93cc-adfccd2eb0b7.png)

**Comment by yuto** [comment]
確認したところ、修正済みのようでした。
