### ISSUE TITLE
軽微な修正について

### ISSUE THREAD

**Issue by hiroin** [sakura-internet/cloud-manual#9]
URL: [リモートアクセス(VPN)設定](https://manual.sakura.ad.jp/cloud/network/vpc-router/vpc-remoteaccess.html)

現状
<p>※いずれも入力必須項目となります
※動的割り当て範囲は、いずれかのプライベートインターフェースに設定したIPアドレス帯に含まれている必要があります</p>

他の書式にあわせた修正
<p>※いずれも入力必須項目となります<br>
※動的割り当て範囲は、いずれかのプライベートインターフェースに設定したIPアドレス帯に含まれている必要があります</p>

**Comment by yuto** [comment]
ご連絡ありがとうございます。
返答が遅れて申し訳ありません。こちら修正完了しております。
